version: '3'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Your secure Password
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command:
      - start
      - --hostname=https://id.kilakubu.de
      - --hostname-strict=false
      - --http-enabled=true
      - --http-port=8080
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: fieguG9e
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: thee3eeS
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: id.kawohl.net
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    networks:
      - traefik-network
      - keycloak-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.keycloak.rule=Host(`id.kilakubu.de`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
#      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
#      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Port=443"
#     - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Host=id.kilakubu.de"
#      - "traefik.http.routers.keycloak.middlewares=keycloak-headers"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
volumes:
  keycloak_data:

networks:
  traefik-network:
    external: true
  keycloak-network: