version: '3'

services:
  synapse_db:
    image: postgres:13
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: 
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
    volumes:
      - ./synapse_data/postgres:/var/lib/postgresql/data
    networks:
      - matrix-network
  
  synapse:
    image: matrixdotorg/synapse:v1.112.0
    user: "991:991"
    volumes:
      - ./synapse_data:/data
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_SERVER_NAME=matrix.kawohl.net
    command: run
    depends_on:
      - synapse_db
    networks:
      - matrix-network
      - traefik-network
      - keycloak-network
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapse.rule=Host(`matrix.kawohl.net`)"
      - "traefik.http.routers.synapse.entrypoints=websecure"
      - "traefik.http.routers.synapse.tls.certresolver=letsencrypt"
      - "traefik.http.services.synapse.loadbalancer.server.port=8008"
#      - "traefik.http.middlewares.synapse-timeouts.forwardauth.authResponseHeaders=IdleConnTimeout,RequestTimeout"
#      - "traefik.http.routers.synapse.middlewares=synapse-timeouts@docker"
  
  element:
    image: vectorim/element-web:v1.11.77
    volumes:
      - ./element_config.json:/app/config.json:ro

    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.element.rule=Host(`element.kawohl.net`)"
      - "traefik.http.routers.element.entrypoints=websecure"
      - "traefik.http.routers.element.tls.certresolver=letsencrypt"
      - "traefik.http.services.element.loadbalancer.server.port=80"

networks:
  matrix-network:
  traefik-network:
    external: true